server:
  port: 9000
spring:
  datasource:
    username: postgres
    password: 12345678
    url: jdbc:postgresql://localhost:5432/course_java_spring
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view:
    hibernate:
      ddl-auto: create
  security:
    user:
      name: admin
      password: 12345
